package com.tiejian147.javase.exception;
/*
关于try...catch中的finally子句：
    1、在finally子句中的代码是最后执行的，并且是一定会执行的，即使try语句块中的代码出现了异常
        finally子句必须和try一起出现，不能单独编写。

    2、finally语句通常使用在那些情况下呢？
 */
public class ExceptionTest10 {
    public static void main(String[] args) {

    }
}
